# LEVEL 10

In [28]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

In [29]:
# Load CSV file into a pandas DataFrame
file_path = "./data/train_data.csv"
data = pd.read_csv(file_path)
data

         MODE POWER   AMPS  VOLTS     TEMP UNIT  DELTA  GAMMA  OUTPUT
0    REDACTED  high  0.585  4.347   66.812    C -0.659 -0.527   3.749
1        beam   low  0.687  2.412  -17.044    C  0.508 -0.371  -1.062
2    REDACTED   low  0.888  2.979   40.918    C  0.600  1.412   2.265
3        auto   low  0.114  0.754  -43.308    C -0.760 -0.109   1.847
4       burst  high  0.318  3.955   37.752    C -0.751  0.492   1.821
..        ...   ...    ...    ...      ...  ...    ...    ...     ...
995      auto   low  0.350  4.257  274.581    K  0.991 -0.335   2.466
996      beam   low  0.644  1.128  -27.707    C -0.529  0.034  -1.834
997     burst   low  0.887  1.418  201.560    ?  0.729 -0.503  -0.188
998  REDACTED   low  0.323  0.291  -17.162    C -0.120  0.524   0.081
999      beam  high  0.344  2.538  -32.986    C  0.075  0.840  -0.379

[1000 rows x 9 columns]

In [30]:
data = data.dropna()

In [31]:
print(sum(data['AMPS'].between(0, 1)))
print(sum(data['VOLTS'].between(0.02, 8.7)))
print(sum(data['TEMP'].between(-100, 373.15)))
print(sum(data['DELTA'].between(-1, 1)))
print(sum(data['GAMMA'].between(-2, 2)))
print(sum(data['OUTPUT'].between(-8.4, 9.3)))

971
984
984
984
984
984

In [32]:
data = data[data['AMPS'].between(0, 1)]
data

         MODE POWER   AMPS  VOLTS     TEMP UNIT  DELTA  GAMMA  OUTPUT
0    REDACTED  high  0.585  4.347   66.812    C -0.659 -0.527   3.749
1        beam   low  0.687  2.412  -17.044    C  0.508 -0.371  -1.062
2    REDACTED   low  0.888  2.979   40.918    C  0.600  1.412   2.265
3        auto   low  0.114  0.754  -43.308    C -0.760 -0.109   1.847
4       burst  high  0.318  3.955   37.752    C -0.751  0.492   1.821
..        ...   ...    ...    ...      ...  ...    ...    ...     ...
995      auto   low  0.350  4.257  274.581    K  0.991 -0.335   2.466
996      beam   low  0.644  1.128  -27.707    C -0.529  0.034  -1.834
997     burst   low  0.887  1.418  201.560    ?  0.729 -0.503  -0.188
998  REDACTED   low  0.323  0.291  -17.162    C -0.120  0.524   0.081
999      beam  high  0.344  2.538  -32.986    C  0.075  0.840  -0.379

[971 rows x 9 columns]

In [33]:
data['AMPS'].describe()

count    971.000000
mean       0.503784
std        0.291678
min        0.000000
25%        0.254500
50%        0.506000
75%        0.760000
max        0.999000
Name: AMPS, dtype: float64

In [34]:
data['POWER_NUM'] = data["VOLTS"]*data["AMPS"]

In [35]:
data2 = data.copy()
data2['TEMP'][data2['UNIT'] == 'C'].describe()

count    649.000000
mean      -1.863952
std       46.083402
min     -100.000000
25%      -34.966000
50%       -2.230000
75%       31.901000
max      100.000000
Name: TEMP, dtype: float64

In [36]:
data2['TEMP'][data2['UNIT'] == 'K'].describe()

count    221.000000
mean     272.459624
std       47.719089
min      173.150000
25%      235.966000
50%      273.212000
75%      306.328000
max      373.150000
Name: TEMP, dtype: float64

In [37]:
data2['TEMP'][(data2['UNIT'] == '?') & (data2['TEMP'] > 100)] = data2['TEMP'][(data2['UNIT'] == '?') & (data2['TEMP'] > 100)] - 273.15
data2['TEMP'][data2['UNIT'] == 'K'] = data2['TEMP'][data2['UNIT'] == 'K'] + -273.15
data2

C:\Users\Murillo\AppData\Local\Temp\ipykernel_20112\4092367807.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['TEMP'][(data2['UNIT'] == '?') & (data2['TEMP'] > 100)] = data2['TEMP'][(data2['UNIT'] == '?') & (data2['TEMP'] > 100)] - 273.15
C:\Users\Murillo\AppData\Local\Temp\ipykernel_20112\4092367807.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['TEMP'][data2['UNIT'] == 'K'] = data2['TEMP'][data2['UNIT'] == 'K'] + -273.15

,MODE,POWER,AMPS,VOLTS,TEMP,UNIT,DELTA,GAMMA,OUTPUT,POWER_NUM
0,REDACTED,high,0.585,4.347,66.812,C,-0.659,-0.527,3.749,2.542995
1,beam,low,0.687,2.412,-17.044,C,0.508,-0.371,-1.062,1.657044
2,REDACTED,low,0.888,2.979,40.918,C,0.600,1.412,2.265,2.645352
3,auto,low,0.114,0.754,-43.308,C,-0.760,-0.109,1.847,0.085956
4,burst,high,0.318,3.955,37.752,C,-0.751,0.492,1.821,1.257690
...,...,...,...,...,...,...,...,...,...,...
995,auto,low,0.350,4.257,1.431,K,0.991,-0.335,2.466,1.489950
996,beam,low,0.644,1.128,-27.707,C,-0.529,0.034,-1.834,0.726432
997,burst,low,0.887,1.418,-71.590,?,0.729,-0.503,-0.188,1.257766
998,REDACTED,low,0.323,0.291,-17.162,C,-0.120,0.524,0.081,0.093993
999,beam,high,0.344,2.538,-32.986,C,0.075,0.840,-0.379,0.873072

In [38]:
data2['TEMP'][data2['UNIT']=='K'].mean().round(2), data2['TEMP'][data2['UNIT']=='K'].std().round(0)

(-0.69, 48.0)

In [39]:
data2['UNIT'][(data2['UNIT'] == '?') & (data2['TEMP'] > 100)] = 'K'
data2['UNIT'][(data2['UNIT'] == '?') & (data2['TEMP'] < 100)] = 'C'

C:\Users\Murillo\AppData\Local\Temp\ipykernel_20112\2739940144.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['UNIT'][(data2['UNIT'] == '?') & (data2['TEMP'] > 100)] = 'K'
C:\Users\Murillo\AppData\Local\Temp\ipykernel_20112\2739940144.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['UNIT'][(data2['UNIT'] == '?') & (data2['TEMP'] < 100)] = 'C'

In [40]:
base_df = data2.copy()

In [41]:
from sklearn import ensemble
from sklearn.inspection import permutation_importance
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import xgboost as xgb
import numpy as np
from sklearn.metrics import auc, accuracy_score, confusion_matrix, mean_squared_error
from sklearn.decomposition import PCA

# XGBoost with OneHotEncoder

In [42]:
from sklearn.preprocessing import OneHotEncoder

data2.reset_index(drop=True, inplace=True)
encoder = OneHotEncoder(sparse=False)
encoded_data = encoder.fit_transform(data2[['POWER', 'UNIT', 'MODE']])
# Create a new DataFrame with the encoded data
df_encoded = pd.DataFrame(encoded_data, columns=encoder.get_feature_names(['POWER', 'UNIT', 'MODE']))

# Concatenate the original DataFrame and the encoded DataFrame
result = pd.concat([data2, df_encoded], axis=1)
# df = df.drop(['UNIT'], axis=1)
data2 = result.drop(['MODE', 'POWER', 'UNIT'], axis=1)
data2

c:\Users\Murillo\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,AMPS,VOLTS,TEMP,DELTA,GAMMA,OUTPUT,POWER_NUM,POWER_high,POWER_low,UNIT_C,UNIT_K,MODE_REDACTED,MODE_auto,MODE_beam,MODE_burst
0,0.585,4.347,66.812,-0.659,-0.527,3.749,2.542995,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,0.687,2.412,-17.044,0.508,-0.371,-1.062,1.657044,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.888,2.979,40.918,0.600,1.412,2.265,2.645352,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
3,0.114,0.754,-43.308,-0.760,-0.109,1.847,0.085956,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.318,3.955,37.752,-0.751,0.492,1.821,1.257690,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,0.350,4.257,1.431,0.991,-0.335,2.466,1.489950,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
967,0.644,1.128,-27.707,-0.529,0.034,-1.834,0.726432,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
968,0.887,1.418,-71.590,0.729,-0.503,-0.188,1.257766,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
969,0.323,0.291,-17.162,-0.120,0.524,0.081,0.093993,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
970,0.344,2.538,-32.986,0.075,0.840,-0.379,0.873072,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [43]:
df = data2
X = df
Y = X['OUTPUT'].values
X = X.drop('OUTPUT', axis = 1).values

In [44]:
xgb_model = xgb.XGBRegressor(objective="reg:squarederror", random_state=0)

In [45]:
xgb_model.fit(X, Y)

y_pred = xgb_model.predict(X)
mse=mean_squared_error(Y, y_pred)

print(np.sqrt(mse))

0.03149934227892787

In [46]:
file_path = "./data/test_data.csv"
df2 = pd.read_csv(file_path)
df2['POWER_NUM'] = df2["VOLTS"]*data["AMPS"]

# Transform the test data using the same encoder instance
encoded_test_data = encoder.transform(df2[['POWER', 'UNIT', 'MODE']])

# Create a new DataFrame with the encoded test data
df_encoded_test  = pd.DataFrame(encoded_test_data, columns=encoder.get_feature_names(['POWER', 'UNIT', 'MODE']))
df2 = pd.concat([df2, df_encoded_test], axis=1)

df2 = df2.drop(['MODE', 'POWER', 'UNIT'], axis=1)
df2

c:\Users\Murillo\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,AMPS,VOLTS,TEMP,DELTA,GAMMA,POWER_NUM,POWER_high,POWER_low,UNIT_C,UNIT_K,MODE_REDACTED,MODE_auto,MODE_beam,MODE_burst
0,0.126,7.489,14.284,-0.818,0.692,4.381065,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,0.917,4.557,17.746,0.251,-0.709,3.130659,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2,0.508,2.928,-9.866,-0.273,1.056,2.600064,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,0.832,2.464,-32.047,0.145,-0.572,0.280896,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.501,2.711,1.349,0.431,-0.939,0.862098,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,0.639,2.318,-21.235,-0.786,0.399,NaN,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2496,0.630,1.569,-12.947,0.768,-0.001,NaN,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2497,0.813,1.854,-29.502,-0.408,0.638,NaN,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
2498,0.172,3.663,-0.141,0.595,0.995,NaN,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
2499,0.644,2.496,45.466,-0.092,-0.130,NaN,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0

In [47]:
y_pred = xgb_model.predict(df2)
np.savetxt('./output/output_XGBoostOneHotEncoding.csv', y_pred)

# XGBoost with categorical

In [48]:
df = base_df.copy()
df["UNIT"] = df["UNIT"].astype("category")
df["MODE"] = df["MODE"].astype("category")
df["POWER"] = df["POWER"].astype("category")
X = df
y = X['OUTPUT']
X = X.drop('OUTPUT', axis = 1)

In [49]:
xgb_model = xgb.XGBRegressor(tree_method="hist", objective="reg:linear", random_state=0, enable_categorical=True)

In [50]:
X

         MODE POWER   AMPS  VOLTS    TEMP UNIT  DELTA  GAMMA  POWER_NUM
0    REDACTED  high  0.585  4.347  66.812    C -0.659 -0.527   2.542995
1        beam   low  0.687  2.412 -17.044    C  0.508 -0.371   1.657044
2    REDACTED   low  0.888  2.979  40.918    C  0.600  1.412   2.645352
3        auto   low  0.114  0.754 -43.308    C -0.760 -0.109   0.085956
4       burst  high  0.318  3.955  37.752    C -0.751  0.492   1.257690
..        ...   ...    ...    ...     ...  ...    ...    ...        ...
995      auto   low  0.350  4.257   1.431    K  0.991 -0.335   1.489950
996      beam   low  0.644  1.128 -27.707    C -0.529  0.034   0.726432
997     burst   low  0.887  1.418 -71.590    C  0.729 -0.503   1.257766
998  REDACTED   low  0.323  0.291 -17.162    C -0.120  0.524   0.093993
999      beam  high  0.344  2.538 -32.986    C  0.075  0.840   0.873072

[971 rows x 9 columns]

In [51]:
xgb_model.fit(X, y)

y_pred = xgb_model.predict(X)
mse=mean_squared_error(y, y_pred)

print(np.sqrt(mse))

[15:05:20] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-08de971ced8a8cdc6-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.

0.022141939240674327

In [52]:
file_path = "./data/test_data.csv"
df2 = pd.read_csv(file_path)
# df2 = df2.drop(['UNIT'], axis=1)
df2["UNIT"] = df2["UNIT"].astype("category")
df2["MODE"] = df2["MODE"].astype("category")
df2["POWER"] = df2["POWER"].astype("category")
df2['POWER_NUM'] = df2["VOLTS"]*data["AMPS"]

In [53]:
y_pred = xgb_model.predict(df2)
np.savetxt('./output/output_XGBoost_Categorical.csv', y_pred)